package Forms.Principal.Salidas.Layouts;

import Forms.Layouts;
import Forms.Principal.Entradas.PanelEntradas;
import Forms.Principal.Entradas.Panels.ConsultarEntradas;
import Forms.Principal.Salidas.Panels.InsertarSalidasPanel;

import javax.swing.*;

/**
 * Clase que hereda de la clase {@link GroupLayout} e implementa la interface {@link Layouts}
 * para el acomodo de componentes y sus dimensiones de su respectivo panel.
 */
public class InsertarSalidasLayout extends GroupLayout implements Layouts {

    //Variable que se encarga de acomodar y dimencionar los componentes en el eje X
        private SequentialGroup Horizontal;
    //Variable que se encarga de acomodar y dimencionar los componentes en el eje Y
        private SequentialGroup Vertical;

        /**
         *
         * Contructor que recibe como parametro una instancia de la clase {@link InsertarSalidasPanel}
         * para ordenar sus componentes con respecto al eje X y Y.
         *
         * @param host {@link InsertarSalidasPanel}
         */
    public InsertarSalidasLayout(InsertarSalidasPanel host) {
        super(host);
        this.Horizontal = this.createSequentialGroup();
        this.Vertical = this.createSequentialGroup();

        this.Horizontal.addGroup(this.createParallelGroup()
                .addGroup(this.createSequentialGroup()
                        .addGap(size_x_mid_productos)
                        .addComponent(host.getFECHA_SALIDA_LB())
                )
                .addGap(20).addGroup(this.createSequentialGroup()
                        .addGap(padding_x2)
                        .addGroup(this.createParallelGroup()
                                .addComponent(host.getCODIGO_BARRAS_LB())
                                .addComponent(host.getN_CODIGO_BARRA(),size_x_min,size_x_mid,size_x_max)
                        ).addGroup(this.createParallelGroup()
                                .addComponent(host.getN_PEDIDO_LB())
                                .addComponent(host.getN_PEDIDO_TXT(),size_x_min,size_x_mid,size_x_max)
                        ).addGroup(this.createParallelGroup()
                                .addComponent(host.getSELLOS_LB())
                                .addComponent(host.getSELLOS_TXT(),size_x_min,size_x_mid,size_x_max)
                        ).addGroup(this.createParallelGroup()
                                .addComponent(host.getCANT_PALLET_LB())
                                .addComponent(host.getCANT_PALLET_TXT(),size_x_min,size_x_mid,size_x_max)
                        )
                        .addGap(padding_x2)
                ).addGap(10).addGroup(this.createSequentialGroup()
                        .addGap(padding_x2)
                        .addGroup(this.createParallelGroup()
                                .addComponent(host.getCANT_POR_PALETT_LB())
                                .addComponent(host.getCANT_POR_PALETT_TXT(),size_x_min,size_x_mid,size_x_max)
                        ).addGroup(this.createParallelGroup()
                                .addComponent(host.getTOTAL_UNIDADES_LB())
                                .addComponent(host.getTOTAL_UNIDADES_TXT(),size_x_min,size_x_mid,size_x_max)
                        ).addGroup(this.createParallelGroup()
                                .addComponent(host.getFECHA_ENTREGA_LB())
                                .addComponent(host.getFECHA_ENTREGA(),size_x_min,size_x_mid,size_x_max)
                        ).addGroup(this.createParallelGroup()
                                .addComponent(host.getDISENO_LB())
                                .addComponent(host.getDISENO_TXT(),size_x_min,size_x_mid,size_x_max)
                        )
                        .addGap(padding_x2)
                ).addGap(10).addGroup(this.createSequentialGroup()
                                .addGap(padding_x2)
                        .addGroup(this.createParallelGroup()
                                .addComponent(host.getPRODUCTO_LB())
                                .addComponent(host.getPRODUCTO_TXT(),size_x_min_productos,
                                        size_x_mid_productos,size_x_max_productos)
                        )
                                .addGap(padding_x2)
                ).addGap(10).addGroup(this.createSequentialGroup()
                        .addGap(padding_x2)
                        .addGroup(this.createParallelGroup()
                                .addComponent(host.getCODIGO_INTERNO_LB())
                                .addComponent(host.getCODIGO_INTERNO_TXT(),size_x_min,size_x_mid,size_x_max)
                        ).addGroup(this.createParallelGroup()
                                .addComponent(host.getCONDICION_LB())
                                .addComponent(host.getCONDICION_CMB(),size_x_min,size_x_mid,size_x_max)
                        ).addGroup(this.createParallelGroup()
                                .addComponent(host.getOBSERVACIONES_LB())
                                .addComponent(host.getOBSERVACIONES_TXT(),size_x_min,size_x_mid,size_x_max)
                        ).addGroup(this.createParallelGroup()
                                .addComponent(host.getCLIENTE_LB())
                                .addComponent(host.getCLIENTE_TXT(),size_x_min,size_x_mid,size_x_max)
                        )
                        .addGap(padding_x2)
                ).addGap(10).addGroup(this.createSequentialGroup()
                        .addGap(padding_x2)
                        .addGroup(this.createParallelGroup()
                                .addComponent(host.getCHOFER_LB())
                                .addComponent(host.getNAME_CHOFER(),size_x_min,size_x_mid,size_x_max)
                        ).addGroup(this.createParallelGroup()
                                .addComponent(host.getEMPRESA_LB())
                                .addComponent(host.getEMPRESA_TXT(),size_x_min,size_x_mid,size_x_max)
                        ).addGroup(this.createParallelGroup()
                                .addComponent(host.getPLACAS_LB())
                                .addComponent(host.getPLACAS_TXT(),size_x_min,size_x_mid,size_x_max)
                        ).addGroup(this.createParallelGroup()
                                .addComponent(host.getTRACTO_LB())
                                .addComponent(host.getTRACTO_TXT(),size_x_min,size_x_mid,size_x_max)
                        )
                        .addGap(padding_x2)
                ).addGap(20).addGroup(this.createSequentialGroup()
                        .addGap(padding_x2)
                        .addGroup(this.createParallelGroup()
                                .addComponent(host.getAGREGAR_A_LA_TABLA_BTN(),size_x_min,size_x_mid,size_x_max)
                        ).addGroup(this.createParallelGroup()
                                .addComponent(host.getELIMINAR_DE_LA_TABLA_BTN(),size_x_min,size_x_mid,size_x_max)
                        ).addGroup(this.createParallelGroup()
                                .addComponent(host.getLIMPIAR_LA_TABLA_BTN(),size_x_min,size_x_mid,size_x_max)
                        ).addGroup(this.createParallelGroup()
                                .addComponent(host.getREGISTRAR_SALIDA_BTN(),size_x_min,size_x_mid,size_x_max)
                        )
                        .addGap(padding_x2)
                ).addGap(20).addGroup(this.createSequentialGroup()
                        .addGap(padding_x2)
                        .addGroup(this.createParallelGroup()
                                .addComponent(host.getTABLA_SALIDAS().getView(),size_x_min_tabla,
                                        size_x_mid_tabla,size_x_max_tabla)
                        )
                        .addGap(padding_x2)
                )
        );

        this.Vertical.addGroup(this.createSequentialGroup()
                .addGap(padding_y_mid/3)
                .addGroup(this.createParallelGroup()
                        .addComponent(host.getFECHA_SALIDA_LB())
                )
                .addGap(20).addGroup(this.createParallelGroup()
                        .addGroup(this.createSequentialGroup()
                                .addComponent(host.getCODIGO_BARRAS_LB())
                                .addComponent(host.getN_CODIGO_BARRA(),size_y_min,size_y_mid,size_y_max)
                        ).addGroup(this.createSequentialGroup()
                                .addComponent(host.getN_PEDIDO_LB())
                                .addComponent(host.getN_PEDIDO_TXT(),size_y_min,size_y_mid,size_y_max)
                        ).addGroup(this.createSequentialGroup()
                                .addComponent(host.getSELLOS_LB())
                                .addComponent(host.getSELLOS_TXT(),size_y_min,size_y_mid,size_y_max)
                        ).addGroup(this.createSequentialGroup()
                                .addComponent(host.getCANT_PALLET_LB())
                                .addComponent(host.getCANT_PALLET_TXT(),size_y_min,size_y_mid,size_y_max)
                        )
                ).addGap(10).addGroup(this.createParallelGroup()
                        .addGroup(this.createSequentialGroup()
                                .addComponent(host.getCANT_POR_PALETT_LB())
                                .addComponent(host.getCANT_POR_PALETT_TXT(),size_y_min,size_y_mid,size_y_max)
                        ).addGroup(this.createSequentialGroup()
                                .addComponent(host.getTOTAL_UNIDADES_LB())
                                .addComponent(host.getTOTAL_UNIDADES_TXT(),size_y_min,size_y_mid,size_y_max)
                        ).addGroup(this.createSequentialGroup()
                                .addComponent(host.getFECHA_ENTREGA_LB())
                                .addComponent(host.getFECHA_ENTREGA(),size_y_min,size_y_mid,size_y_max)
                        ).addGroup(this.createSequentialGroup()
                                .addComponent(host.getDISENO_LB())
                                .addComponent(host.getDISENO_TXT(),size_y_min,size_y_mid,size_y_max)
                        )
                ).addGap(10).addGroup(this.createParallelGroup()
                        .addGroup(this.createSequentialGroup()
                                .addComponent(host.getPRODUCTO_LB())
                                .addComponent(host.getPRODUCTO_TXT(),size_y_min,size_y_mid,size_y_max)
                        )
                ).addGap(10).addGroup(this.createParallelGroup()
                        .addGroup(this.createSequentialGroup()
                                .addComponent(host.getCODIGO_INTERNO_LB())
                                .addComponent(host.getCODIGO_INTERNO_TXT(),size_y_min,size_y_mid,size_y_max)
                        ).addGroup(this.createSequentialGroup()
                                .addComponent(host.getCONDICION_LB())
                                .addComponent(host.getCONDICION_CMB(),size_y_min,size_y_mid,size_y_max)
                        ).addGroup(this.createSequentialGroup()
                                .addComponent(host.getOBSERVACIONES_LB())
                                .addComponent(host.getOBSERVACIONES_TXT(),size_y_min,size_y_mid,size_y_max)
                        ).addGroup(this.createSequentialGroup()
                                .addComponent(host.getCLIENTE_LB())
                                .addComponent(host.getCLIENTE_TXT(),size_y_min,size_y_mid,size_y_max)
                        )
                ).addGap(10).addGroup(this.createParallelGroup()
                        .addGroup(this.createSequentialGroup()
                                .addComponent(host.getCHOFER_LB())
                                .addComponent(host.getNAME_CHOFER(),size_y_min,size_y_mid,size_y_max)
                        ).addGroup(this.createSequentialGroup()
                                .addComponent(host.getEMPRESA_LB())
                                .addComponent(host.getEMPRESA_TXT(),size_y_min,size_y_mid,size_y_max)
                        ).addGroup(this.createSequentialGroup()
                                .addComponent(host.getPLACAS_LB())
                                .addComponent(host.getPLACAS_TXT(),size_y_min,size_y_mid,size_y_max)
                        ).addGroup(this.createSequentialGroup()
                                .addComponent(host.getTRACTO_LB())
                                .addComponent(host.getTRACTO_TXT(),size_y_min,size_y_mid,size_y_max)
                        )
                ).addGap(20).addGroup(this.createParallelGroup()
                        .addGap(padding_x2)
                        .addGroup(this.createSequentialGroup()
                                .addComponent(host.getAGREGAR_A_LA_TABLA_BTN(),size_y_min,size_y_mid,size_y_max)
                        ).addGroup(this.createSequentialGroup()
                                .addComponent(host.getELIMINAR_DE_LA_TABLA_BTN(),size_y_min,size_y_mid,size_y_max)
                        ).addGroup(this.createSequentialGroup()
                                .addComponent(host.getLIMPIAR_LA_TABLA_BTN(),size_y_min,size_y_mid,size_y_max)
                        ).addGroup(this.createSequentialGroup()
                                .addComponent(host.getREGISTRAR_SALIDA_BTN(),size_y_min,size_y_mid,size_y_max)
                        )
                        .addGap(padding_x2)
                )
                .addGap(20).addGroup(this.createParallelGroup()
                        .addGap(padding_x2)
                        .addGroup(this.createSequentialGroup()
                                .addGap(10)
                                .addComponent(host.getTABLA_SALIDAS().getView(),size_y_min_tabla,
                                        size_y_mid_tabla,size_y_max_tabla)
                                .addGap(20)
                        )
                        .addGap(padding_x2)
                )
        );


        this.setVerticalGroup(this.Vertical);
        this.setHorizontalGroup(this.Horizontal);
    }
}
