package Forms.Principal.Entradas.Layouts;

import Forms.Principal.Entradas.PanelEntradas;
import Forms.Principal.Entradas.Panels.InsertarEntradas;
import Forms.Layouts;

import javax.swing.*;

/**
 * Clase que hereda de la clase {@link GroupLayout} e implementa la interface {@link Layouts}
 * para el acomodo de componentes y sus dimensiones de su respectivo panel.
 */
public class InsertarEntradasLayout extends GroupLayout implements Layouts {

    //Variable que se encarga de acomodar y dimencionar los componentes en el eje X
    private SequentialGroup Horizontal;
    //Variable que se encarga de acomodar y dimencionar los componentes en el eje Y
    private SequentialGroup Vertical;

    /**
     *
     * Contructor que recibe como parametro una instancia de la clase {@link InsertarEntradas}
     * para ordenar sus componentes con respecto al eje X y Y.
     *
     * @param host {@link PanelEntradas}
     */
    public InsertarEntradasLayout(InsertarEntradas host) {
        super(host);

        this.Horizontal = this.createSequentialGroup();
        this.Vertical   = this.createSequentialGroup();

        this.Horizontal.addGroup(this.createParallelGroup()
                .addGap(30)
                .addGroup(this.createSequentialGroup()
                        .addGap(padding_x2)
                        .addGroup(this.createParallelGroup()
                                .addComponent(host.getN_ORDEN_LB())
                                .addComponent(host.getN_ORDEN_TXT(),size_x_min,size_x_mid,size_x_max)
                        )
                        .addGap(10)
                        .addGroup(this.createParallelGroup()
                                .addComponent(host.getN_PEDIDO_LB())
                                .addComponent(host.getN_PEDIDO_TXT(),size_x_min,size_x_mid,size_x_max)
                        )
                        .addGap(150)
                        .addComponent(host.getFECHA_ENTRADA_LB())

                )
                .addGap(10)
                .addGroup(this.createSequentialGroup()
                        .addGap(padding_x2)
                        .addGroup(this.createParallelGroup()
                                .addComponent(host.getCODIGO_DE_BARRAS_LB())
                                .addComponent(host.getCODIGO_DE_BARRAS_CMB(),size_x_min,size_x_mid,size_x_max)
                        )
                        .addGap(10)
                        .addGroup(this.createParallelGroup()
                                .addComponent(host.getDISENO_LB())
                                .addComponent(host.getDISENO_TXT(),size_x_min,size_x_mid,size_x_max)
                        )
                        .addGap(10)
                        .addGroup(this.createParallelGroup()
                                .addComponent(host.getCODIGO_INTERNO_LB())
                                .addComponent(host.getCODIGO_INTERNO_TXT(),size_x_min,size_x_mid,size_x_max)
                        )
                        .addGap(10)
                        .addGroup(this.createParallelGroup()
                                .addComponent(host.getCLIENTE_LB())
                                .addComponent(host.getCLIENTE_TXT(),size_x_min,size_x_mid,size_x_max)
                        )
                        .addGap(30)
                )
                .addGap(10)
                .addGroup(this.createSequentialGroup()
                        .addGap(padding_x2)
                        .addGroup(this.createParallelGroup()
                                .addComponent(host.getPRODUCTO_LB())
                                .addComponent(host.getPRODUCTO_TXT(),size_x_min_productos,size_x_mid_productos,size_x_max_productos)
                        )
                        .addGap(160)
                )
                .addGap(10)
                .addGroup(this.createSequentialGroup()
                        .addGap(padding_x2)
                        .addGroup(this.createParallelGroup()
                                .addComponent(host.getCANT_PALLET_LB())
                                .addComponent(host.getCANT_PALLET_TXT(),size_x_min,size_x_mid,size_x_max)
                        )
                        .addGap(10)
                        .addGroup(this.createParallelGroup()
                                .addComponent(host.getCANT_POR_PALETT_LB())
                                .addComponent(host.getCANT_POR_PALETT_TXT(),size_x_min,size_x_mid,size_x_max)
                        )
                        .addGap(10)
                        .addGroup(this.createParallelGroup()
                                .addComponent(host.getOBSERVACIONES_LB())
                                .addComponent(host.getOBSERVACIONES_TXT(),size_x_min,size_x_mid,size_x_max)
                        )
                        .addGap(10)
                        .addGroup(this.createParallelGroup()
                                .addComponent(host.getCONDICION_LB())
                                .addComponent(host.getCONDICION_CMB(),size_x_min,size_x_mid,size_x_max)
                        )
                        .addGap(30)
                )
                .addGap(10)
                .addGroup(this.createSequentialGroup()
                        .addGap(padding_x2)
                        .addGroup(this.createParallelGroup()
                                .addComponent(host.getCHOFER_LB())
                                .addComponent(host.getCHOFER_CMB(),size_x_min,size_x_mid,size_x_max)
                        )
                        .addGap(10)
                        .addGroup(this.createParallelGroup()
                                .addComponent(host.getEMPRESA_LB())
                                .addComponent(host.getEMPRESA_TXT(),size_x_min,size_x_mid,size_x_max)
                        )
                        .addGap(10)
                        .addGroup(this.createParallelGroup()
                                .addComponent(host.getPLACAS_LB())
                                .addComponent(host.getPLACAS_TXT(),size_x_min,size_x_mid,size_x_max)
                        )
                        .addGap(10)
                        .addGroup(this.createParallelGroup()
                                .addComponent(host.getTRACTO_LB())
                                .addComponent(host.getTRACTO_TXT(),size_x_min,size_x_mid,size_x_max)
                        )

                        .addGap(30)
                )
                .addGap(10)
                .addGroup(this.createSequentialGroup()
                        .addGap(padding_x2)
                        .addGroup(this.createParallelGroup()
                                .addComponent(host.getCANTIDAD_FOLIOS_LB())
                                .addComponent(host.getCANTIDAD_FOLIOS_TXT(),size_x_min,size_x_mid,size_x_max)
                        )
                        .addGap(30)
                )
                .addGap(10)
                .addGroup(this.createSequentialGroup()
                        .addGap(padding_x2)
                        .addComponent(host.getAGREGAR(),size_x_min,size_x_mid,size_x_max)
                        .addGap(10)
                        .addComponent(host.getGUARDAR(),size_x_min,size_x_mid,size_x_max)
                        .addGap(10)
                        .addComponent(host.getELIMINAR(),size_x_min,size_x_mid,size_x_max)
                        .addGap(10)
                        .addComponent(host.getLIMPIAR_TABLA(),size_x_min,size_x_mid,size_x_max)
                        .addGap(30)
                )
                .addGap(10)
                .addGroup(this.createSequentialGroup()
                        .addGap(padding_x2)
                        .addGroup(this.createParallelGroup()
                                .addGap(30)
                                .addComponent(host.getTABLA_DE_ENTRADAS().getView(),size_x_min_tabla,size_x_mid_tabla,size_x_max_tabla)
                                .addGap(30)
                        )
                        .addGap(30)
                )
                .addGap(10)

        );

        this.Vertical.addGroup(this.createSequentialGroup()
                .addGap(30)
                .addGroup(this.createParallelGroup()
                        .addGap(30)
                        .addGroup(this.createSequentialGroup()
                                .addComponent(host.getN_ORDEN_LB())
                                .addComponent(host.getN_ORDEN_TXT(),size_y_min,size_y_mid,size_y_max)
                        )
                        .addGap(10)
                        .addGroup(this.createSequentialGroup()
                                .addComponent(host.getN_PEDIDO_LB())
                                .addComponent(host.getN_PEDIDO_TXT(),size_y_min,size_y_mid,size_y_max)
                        )
                        .addComponent(host.getFECHA_ENTRADA_LB())
                )
                .addGap(10)
                .addGroup(this.createParallelGroup()
                        .addGap(30)
                        .addGroup(this.createSequentialGroup()
                                .addComponent(host.getCODIGO_DE_BARRAS_LB())
                                .addComponent(host.getCODIGO_DE_BARRAS_CMB(),size_y_min,size_y_mid,size_y_max)
                        )
                        .addGap(10)
                        .addGroup(this.createSequentialGroup()
                                .addComponent(host.getDISENO_LB())
                                .addComponent(host.getDISENO_TXT(),size_y_min,size_y_mid,size_y_max)
                        )
                        .addGap(10)
                        .addGroup(this.createSequentialGroup()
                                .addComponent(host.getCODIGO_INTERNO_LB())
                                .addComponent(host.getCODIGO_INTERNO_TXT(),size_y_min,size_y_mid,size_y_max)
                        )
                        .addGap(10)
                        .addGroup(this.createSequentialGroup()
                                .addComponent(host.getCLIENTE_LB())
                                .addComponent(host.getCLIENTE_TXT(),size_y_min,size_y_mid,size_y_max)
                        )
                        .addGap(30)
                )
                .addGap(10)
                .addGroup(this.createParallelGroup()
                        .addGap(30)
                        .addGroup(this.createSequentialGroup()
                                .addComponent(host.getPRODUCTO_LB())
                                .addComponent(host.getPRODUCTO_TXT(),size_y_min,size_y_mid,size_y_max)
                        )
                        .addGap(30)
                )
                .addGap(10)
                .addGroup(this.createParallelGroup()
                        .addGap(30)
                        .addGroup(this.createSequentialGroup()
                                .addComponent(host.getCANT_PALLET_LB())
                                .addComponent(host.getCANT_PALLET_TXT(),size_y_min,size_y_mid,size_y_max)
                        )
                        .addGap(10)
                        .addGroup(this.createSequentialGroup()
                                .addComponent(host.getCANT_POR_PALETT_LB())
                                .addComponent(host.getCANT_POR_PALETT_TXT(),size_y_min,size_y_mid,size_y_max)
                        )
                        .addGap(10)
                        .addGroup(this.createSequentialGroup()
                                .addComponent(host.getOBSERVACIONES_LB())
                                .addComponent(host.getOBSERVACIONES_TXT(),size_y_min,size_y_mid,size_y_max)
                        )
                        .addGap(10)
                        .addGroup(this.createSequentialGroup()
                                .addComponent(host.getCONDICION_LB())
                                .addComponent(host.getCONDICION_CMB(),size_y_min,size_y_mid,size_y_max)
                        )
                        .addGap(30)
                )
                .addGap(10)
                .addGroup(this.createParallelGroup()
                        .addGap(30)
                        .addGroup(this.createSequentialGroup()
                                .addComponent(host.getCHOFER_LB())
                                .addComponent(host.getCHOFER_CMB(),size_y_min,size_y_mid,size_y_max)
                        )
                        .addGap(10)
                        .addGroup(this.createSequentialGroup()
                                .addComponent(host.getEMPRESA_LB())
                                .addComponent(host.getEMPRESA_TXT(),size_y_min,size_y_mid,size_y_max)
                        )
                        .addGap(10)
                        .addGroup(this.createSequentialGroup()
                                .addComponent(host.getPLACAS_LB())
                                .addComponent(host.getPLACAS_TXT(),size_y_min,size_y_mid,size_y_max)
                        )
                        .addGap(10)
                        .addGroup(this.createSequentialGroup()
                                .addComponent(host.getTRACTO_LB())
                                .addComponent(host.getTRACTO_TXT(),size_y_min,size_y_mid,size_y_max)
                        )


                )
                .addGap(10)
                .addGroup(this.createParallelGroup()
                        .addGap(30)
                        .addGroup(this.createSequentialGroup()
                                .addComponent(host.getCANTIDAD_FOLIOS_LB())
                                .addComponent(host.getCANTIDAD_FOLIOS_TXT(),size_y_min,size_y_mid,size_y_max)
                        )
                        .addGap(30)
                )
                .addGap(10)
                .addGroup(this.createParallelGroup()
                        .addGap(10)
                        .addComponent(host.getAGREGAR(),size_y_min,size_y_mid,size_y_max)
                        .addGap(10)
                        .addComponent(host.getGUARDAR(),size_y_min,size_y_mid,size_y_max)
                        .addGap(10)
                        .addComponent(host.getELIMINAR(),size_y_min,size_y_mid,size_y_max)
                        .addGap(10)
                        .addComponent(host.getLIMPIAR_TABLA(),size_y_min,size_y_mid,size_y_max)
                        .addGap(30)
                )
                .addGap(10)
                .addGroup(this.createParallelGroup()
                        .addGap(30)
                        .addGroup(this.createSequentialGroup()

                                .addComponent(host.getTABLA_DE_ENTRADAS().getView(),size_y_min_tabla/2,size_y_mid_tabla,size_y_mid_tabla)
                                .addGap(30)
                        )
                        .addGap(30)
                )
                .addGap(10)

        );

        this.setHorizontalGroup(this.Horizontal);
        this.setVerticalGroup(this.Vertical);

    }
}
